### ISSUE TITLE
error :(

### ISSUE THREAD

**Issue by b4zz4** [htho/scadlib#2]
$ python scadtool.py info testing/information-extraction-example.scad 

Traceback (most recent call last):
  File "scadtool.py", line 351, in <module>
    cmd_info_handler(args)
  File "scadtool.py", line 32, in cmd_info_handler
    scadLibrary = lib.ScadLibrary(args.INPUT_FILE_OR_DIR, args.recursive, args.traverse_dirs)
  File "/home/user/src/fzz2scad/scadlib/scadtoolLib.py", line 1485, in **init**
    self.fileList.append(ScadFileFromFile.buildFromFile(source, recursive=recursive, referencedFromScadFile=None))
  File "/home/user/src/fzz2scad/scadlib/scadtoolLib.py", line 954, in buildFromFile
    return ScadFileFromFile(content=f.read(), path=path, referencedFromScadFile=referencedFromScadFile, recursive=recursive)
  File "/home/user/src/fzz2scad/scadlib/scadtoolLib.py", line 1002, in **init**
    metaData.makeFileDoc()
  File "/home/user/src/fzz2scad/scadlib/scadtoolLib.py", line 503, in makeFileDoc
    self.__reBuildDicts()
  File "/home/user/src/fzz2scad/scadlib/scadtoolLib.py", line 469, in __reBuildDicts
    value = str(value).split(sep=None, maxsplit=1)
TypeError: split() takes no keyword arguments

**Comment by b4zz4** [comment]
to use python3 :D

**Comment by htho** [comment]
I am an ArchLinux User. Python3 is standard there since [10/2010](https://www.archlinux.org/news/python-is-now-python-3/). I am so used to it - I take it for granted.
